apiVersion: v1
kind: Service
metadata:
  name: image-quote-service
spec:
  type: NodePort
  selector:
    app: image-quote-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
